version: '3'
services:
  user-app:
    image: user-app
    build: accountmanager/
    restart: always
    network_mode: host
    ports:
      - 8089:8089
    expose:
      - 8089
    depends_on:
      - muzix-mysql
  muzix-app:
    image: muzix-app
    build: muzixmanager/
    restart: always
    network_mode: host
    ports:
      - 8082:8082
    expose:
      - 8082
    depends_on:
      - muzix-mysql
  muzix-mysql:
   image: mysql:5.6
   network_mode: host
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: muzixDb
     MYSQL_USER: app_root
     MYSQL_PASSWORD: root123
  muzix-angular-app:
    image: muzix-angular-app
    build: MuzixUI/
    network_mode: host
    container_name: muzix-angular-docker
    ports:
      - 4200:4200
    expose:
      - 4200

